### ISSUE TITLE
AppMaps recorded only include API information

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-node#107]
[Using this project:](https://github.com/land-of-apps/mern-ecommerce#running-locally)
Node version: v18.19.0
appmap-node version: 2.14.2

[My appmap.yml example](https://github.com/land-of-apps/mern-ecommerce/blob/master/appmap.yml#L1-L7)

Starting AppMap + the application using `npx appmap-node@2.14.2 npm run dev`

As i interact with the application, (login, register user, etc) I get the following AppMaps, but they are missing function details and only show the API calls.  

Two example appmaps below - one remote recording, one request recording. 

[Admin_login.appmap.json.zip](https://github.com/getappmap/appmap-node/files/14088987/Admin_login.appmap.json.zip)
[2024-01-29T19:59:01.783Z_-api-auth-login.appmap.json.zip](https://github.com/getappmap/appmap-node/files/14088989/2024-01-29T19.59.01.783Z_-api-auth-login.appmap.json.zip)

<img width="1212" alt="Screenshot 2024-01-29 at 1 55 03 PM" src="https://github.com/getappmap/appmap-node/assets/511733/cced45e6-863e-4a91-8f54-3244839488fd">

**Comment by dividedmind** [comment]
Ah. This is because the project has _almost no functions_. O_o

**Comment by petecheslock** [comment]
Ahh gotcha.  Thanks for checking @dividedmind.  I'll continue the search for some good MERN projects.
