### ISSUE TITLE
Prisma support

### ISSUE THREAD

**Issue by dividedmind** [getappmap/appmap-node#79]
[Prisma](https://www.prisma.io/) is a rich JS ORM that does sophisticated code manipulation under the hood to provide convenient and safe developer experience. We haven't tried it but it seems to use internal SQL clients instead of the libraries we already hook, which means the SQL queries executed with Prisma won't currently get captured.

**Comment by dustinbyrne** [comment]
@zermelo-wisen Is this in progress?
