### ISSUE TITLE
Optionally capture HTTP response body

### ISSUE THREAD

**Issue by dividedmind** [getappmap/appmap-node#81]
Capturing HTTP response body is a feature that's frequently requested by our users. While it's probably too much overhead to do it by default, it could be optionally enabled (eg. with an `APPMAP_CAPTURE_HTTP_RESPONSE=<max length>` environment variable). It seems like it can simply go into the `return_value` of the HTTP response event.

Note this is not necessarily trivial since the app can stream the response. It likely involves replacing the response stream with a tee that sends both to the peer and to appmap.

**Comment by kgilpin** [comment]
This feature is often requested and IMO can be on by default.
