### ISSUE TITLE
Mapping "archive" command doesn't include a top-level command function in the AppMap

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-node#92]
```
npx appmap-node node ./built/cli.js archive
```

I'm expecting to see the archive command at the root of the AppMap.

[2024-01-17T15_16_04.479Z.appmap.json](https://github.com/getappmap/appmap-node/files/13966142/2024-01-17T15_16_04.479Z.appmap.json)

[appmap.yml.zip](https://github.com/getappmap/appmap-node/files/13966158/appmap.yml.zip)

**Comment by dividedmind** [comment]
Do you mean the `handler` here? https://github.com/getappmap/appmap-js/blob/ad1903178c2f321f1078a4131acd1ba7516d7d95/packages/cli/src/cmds/archive/archive.ts#L110

We're only capturing `function`s currently; this was kind of a deliberate in the hope of skipping some cruft utility functions. Do you think we should expand to named const lambdas?

**Comment by kgilpin** [comment]
IMO hooking a const lambda is only necessary if it’s exported.

**Comment by zermelo-wisen** [comment]
I believe this is resolved, since we are now capturing lambdas as well. This is captured as "handler" in the AppMap.

![image](https://github.com/getappmap/appmap-node/assets/98758224/e4504e68-0a83-4e3c-9fc4-e9161aa07be7)

**Comment by dividedmind** [comment]
> I believe this is resolved, since we are now capturing lambdas as well. This is captured as "handler" in the AppMap.

Yup, thanks for the triage! Fixed by #109
